### ISSUE TITLE
[FE]로그인 기능

### ISSUE THREAD

**Issue by journey0321** [codestates-seb/seb42_main_019#32]
## 만들고자 하는 기능
로그인 기능

<br>  

## 기능의 설명
웹 사이트 로그인

<br> 

## Todo  
1. [x] 로그인 사용자가 입력한 폼 저장
2. [x] 핸들러 추가
3. [x] 서버 통신 및 인증 결과 처리
4. [x] 인증 토큰 생성 확인, 사용자 식별 확인

**Comment by journey0321** [comment]
구현완료

**Comment by journey0321** [comment]
구현완료
